apiVersion: tekton.dev/v1beta1
kind: PipelineRun 
metadata: 
  generateName: pipeline1-run
  labels:
    teir: sample
    data: pipeline1
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: ark-pipes
  
  params:
    - name: gitUrl
      value: https://github.com/arislanIOT/get-started-node.git
    - name: build_image
      value: quay.io/buildah/stable:latest
    - name: imageUrl
      value: us.icr.io/initial_namespace/nodes
    - name: imageTag
      value: s390x-latest
    - name: storage_driver
      value: vfs
  
  workspaces:
    - name:  sourcecode-storage
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1G
