apiVersion: tekton.dev/v1beta1
kind: Task 
metadata:
  name: push
  labels:
    teir: sample
    data: pipeline1
  
spec:
  workspaces:
    - name: source
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built. 

  params:
    - name: BUILDER_IMAGE
      description: Builder Image 
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: STORAGE_DRIVER
      description: buildah storage driver 
      default: overlay

  steps:
    - name: pushing
      image: $(params.BUILDER_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        echo  "Pushing started as Task"
        buildah --storage-driver=$(params.STORAGE_DRIVER) push --digestfile $(workspaces.source.path)/image-digest  $(params.IMAGE) docker://$(params.IMAGE)

      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers

      securityContext:
          privileged: true

  volumes:
    - name: varlibcontainers
      emptyDir: {}