apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
  - name: header
    description: The event header
  - name: body
    description: The event body
  resourcetemplates:

  - apiVersion: v1 
    kind: Secret
    metadata:
      name: icr-ark 
      annotations:
        tekton.dev/docker-0: https://us.icr.io
    type: kubernetes.io/dockerconfigjson
    data:
      .dockerconfigjson: eyJhdXRocyI6eyJ1cy5pY3IuaW8vaW5pdGlhbF9uYW1lc3BhY2UiOnsidXNlcm5hbWUiOiJpYW1hcGlrZXkiLCJwYXNzd29yZCI6ImhncmtGaTZVbHNOS01WRFRJRlRMOWdPTkdIeTNtVGFsenFPWVhBRnVDbXJPIiwiZW1haWwiOiJhcmlzbGFuQGlibS5jb20iLCJhdXRoIjoiYVdGdFlYQnBhMlY1T21obmNtdEdhVFpWYkhOT1MwMVdSRlJKUmxSTU9XZFBUa2RJZVROdFZHRnNlbkZQV1ZoQlJuVkRiWEpQIn19fQ==

  - apiVersion: v1 
    kind: ServiceAccount
    metadata:
      name: build-bot
    secrets:
      - name: icr-ark  
  
  - apiVersion: v1 
    kind: PersistentVolumeClaim
    metadata:
      name: agentbuild-$(uid)-pvc
    spec:
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
        
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata: 
      generateName: pipeline1-run
      labels:
        teir: sample
        data: pipeline1
    spec:
      serviceAccountNames: 
        - taskName: build
          serviceAccountName: build-bot
      pipelineRef:
        name: ark-pipes
      
      params:
        - name: gitUrl
          value: https://github.com/arislanIOT/think-tekton-authoring.git
        - name: build_image
          value: quay.io/buildah/stable:latest
        - name: imageUrl
          value: us.icr.io/initial_namespace/nodes
        - name: imageTag
          value: s390x-latest
        - name: storage_driver
          value: vfs
      
      workspaces:
        - name:  sourcecode-storage
          persistentVolumeClaim:
            claimName: agentbuild-$(uid)-pvc